name = "DiscreteExteriorCalculus"
uuid = "0a3a9624-8642-11e9-0f42-fd2a0d40ec72"
authors = ["Michael Scheer <mgscheer@gmail.com>", "H-Fukagawa <あなたのEmailなど>"] # 必要に応じて更新
# バージョン番号を上げる (例: v0.1.1 -> v0.2.0)
# セマンティックバージョニングに従い、互換性のない変更があればメジャーバージョンを上げる (例: v1.0.0)
version = "0.2.0" # または "1.0.0" など

# ランタイムの依存関係
[deps]
# AdmittanceModels は更新済みのバージョン(例: 0.3)を想定 →　コメントアウト
# AdmittanceModels = "5eda1363-42a2-4d75-bc45-7e2a4a7b92b2"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UniqueVectors = "2fbcfb34-fd0c-5fbb-b5d7-e826d8f5b0a9"
# 標準ライブラリ (明示的に記載)
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

# 互換性情報 (現代的に更新)
[compat]
# Julia 本体: v1.6 以降を想定
julia = "1.6 - 1.12"

# 依存パッケージの互換バージョン (現在の安定版を想定した例)
# 【重要】AdmittanceModels が v0.3.0 に更新されたと仮定
AdmittanceModels = "0.3"
Combinatorics = "1"
MatrixNetworks = "1"      # 要注意: 更新が止まっている可能性
StaticArrays = "1"
UniqueVectors = "1"
# 標準ライブラリ
LinearAlgebra = "1"
SparseArrays = "1"
Statistics = "1"

# テストやドキュメント生成用の依存関係
[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test"]
# ドキュメントを Documenter.jl で生成する場合
# docs = ["Documenter"]
